### ISSUE TITLE
Writing Articles and sections

### ISSUE THREAD

**Issue by EMCP** [JesusGuerrero/MAHRIO#83]
When creating a new article I had a section of text under one of the option decks, in this case the 3rd..

I inadvertently lost that text because I had not hit the `+` button to add it to the article.  It would be good to warn an article writer that they have unsaved text in a deck if they don't go and hit the `+` button

**Comment by EMCP** [comment]
![screen shot 2015-12-19 at 12 43 09 pm](https://cloud.githubusercontent.com/assets/3691722/11915141/23159786-a64e-11e5-8a01-72ceb7c47ef9.png)

**Comment by EMCP** [comment]
also, source link should be clickable

**Comment by EMCP** [comment]
another note, a movable icon doesn't seem to work .  I click drag it and nothing moves

is this supposed to be able to move the deck?


![screen shot 2015-12-19 at 12 53 58 pm](https://cloud.githubusercontent.com/assets/3691722/11915178/a7dde33c-a64f-11e5-9387-c10d14cb75b2.png)

**Comment by JesusGuerrero** [comment]
will work to improve this tonight. The moveable icon needs to be clicked and it allows moving the rows vertically to rearrange. only thing fixing here is preventing the submission when text is in the text area of section and not added to prevent losing work

**Comment by JesusGuerrero** [comment]
issue resolved.
