### ISSUE TITLE
Linking to articles not quite loading

### ISSUE THREAD

**Issue by EMCP** [JesusGuerrero/MAHRIO#85]
Not sure if we're requiring people to be logged in to read articles, or use HTTP or HTTPS .. but this is what I'm seeing when clicking from twitter

On Desktop it's just grey, on mobile it partially loads
![screenshot_20151219-223529](https://cloud.githubusercontent.com/assets/3691722/11916892/b4d9e8d6-a6a1-11e5-8c6a-bc595ea1afd6.png)

The tweet in question
![screen shot 2015-12-19 at 10 34 34 pm](https://cloud.githubusercontent.com/assets/3691722/11916873/b1f7843a-a6a0-11e5-89f4-2e5eca68bf22.png)

**Comment by JesusGuerrero** [comment]
You can update linkage. twitter card info now available on the articles. Close this ticket after
